image: node:10

build:  
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install --quiet
    - npm run build
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  environment: 
    name: production
  only: 
   - master
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run build
  image: docker:stable
  services:
  - docker:dind  
  stage: build
  script:
  - docker login -u nishranjan -p nimeRA@25 registry.gitlab.com/ssanushka/fab_client
  - docker build -t registry.gitlab.com/ssanushka/fab_client:latest .
  - docker push registry.gitlab.com/ssanushka/fab_client:latest
  
